title: "Ricardo I Alcala Briseno - Virome ecology"
email: "ria5282[at]psu.edu"
keywords: "virus discovery, virome abalysis, funtional diversity, community ecology, network analysis"
description: "Personal website of Ricardo I Alcala"
url: "https://ricardoi.github.io"
favicon: "img/PSU-logo.png"
touch_icon: "img/apple-touch-icon.png"
google_analytics_key: "3d73f6c4a7f91f185cfff7311a4746fa35d68a17"
highlighter: rouge
markdown: kramdown

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  dark:      '#313437'
  lightgray: '#E0E0E0'
  white:     '#FFFFFF'
  white0:    '#ebebeb'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

github: { metadata: false }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-scholar

exclude:
  - vendor
  - vendor/**
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - Rakefile

# Bibliography settings
scholar:
  last_name: Alcalá Briseño
  locale: en
  sort_by: year,month
  order: descending
  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib

